### ISSUE TITLE
ValueError: Invalid format string

### ISSUE THREAD

**Issue by Kryhowsky** [twintproject/twint#605]
### Initial Check
- Python version is 3.6;
- Updated Twint with `pip3 install --user --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint`;
- I have searched the issues and there are no duplicates of this issue/question/request.

### Command Ran
>twint -s #protein --since 2019-11-01 --until 2019-11-30 -o tweets.json --json

### Description of Issue
>When I run this command in cmd I got an error: 
**ValueError: Invalid format string.**

Same situation is when I'm trying to run python script with twint as a module. When c.Since and c.Until is specified there is error. When I scpecify only one argument (doesn't matter if it is a since or until) script runs.

### Environment Details
>I'm using Windows and running this in terminal.

**Comment by pielco11** [comment]
That issue has been fixed yesterday, are you sure to be running the latest version?

**Comment by Kryhowsky** [comment]
I updated repository once again and durig this is warning **WARNING: Did not find branch or tag 'origin/master', assuming revision or ref.** 
Maby it's something with that? Because I did it again and still have ValueError. I copy pasted url.py as well. Same ValueError again.

**Comment by pielco11** [comment]
Copying&pasting is a bad practice, and I do not suggest it. (you are modifying data, modifications should be commit-ed and so on...)

May you clone twint a new directory and erase the previous one?

**Comment by Kryhowsky** [comment]
Sure, I did it. Created new directory and clone git once again.
Still have this error.
Maybe this will say more about this ValueError?
**CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)**

**Comment by pielco11** [comment]
This error message is known and there's not a solution for it, yet. So you can just ignore it

**Comment by Kryhowsky** [comment]
Ok, but if I run same script on machine with other OS that should works?

**Comment by pielco11** [comment]
Ignoring that error message, people told me that Twint works as expected with every platform. That command is expected to work on both Windows and *nix systems
